version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app:cached
      - /app/node_modules
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
