version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_DB=webframeworkdb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    volumes:
    - ../backend:/app
    command: gunicorn -w 1 -b 0.0.0.0:8000 backend.wsgi:application --reload
