version: "3.7"

volumes:
  database_data:
    driver: local

services:
  postgres:
    container_name: database
    build: ../dockerfiles/database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=webframeworkdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
